name: Toolbox.Inspections

on:
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUILD_VERSION: "0.1.${{ github.run_number }}"

jobs:

  build:
    name: Build
    runs-on: windows-latest  

    steps:
    # - name: List env
    #  run: env
      
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    # - name: Echo Version 
    #  run: echo "Version = ${{ env.BUILD_VERSION }}"
    
    - name: Version Visual Studio SDK projects
      uses: roryprimrose/set-vs-sdk-project-version@v1.0.3
      with:
        version: "${{ env.BUILD_VERSION }}.0"
        assemblyVersion: "${{ env.BUILD_VERSION }}.0"
        fileVersion: "${{ env.BUILD_VERSION }}.0"
        informationalVersion: "${{ env.BUILD_VERSION }}.0"
    
    # Compile the solution
    - name: Compile solution
      run: dotnet build src\Toolbox.Inspections.sln -c Release -o output

    - name: Remove unnecessary files
      run: del output\*.pdb,output\*.dev.json,output\*.deps.json 
    
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: output
      
  pack_release:
    name: Pack Release
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download output
      uses: actions/download-artifact@v3
      with:
        name: output
        path: output
    
    - name: Pack binaries
      uses: TheDoctor0/zip-release@0.6.2
      with:
        filename: 'binary.zip'
        path: output
        type: 'zip'

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: binary.zip
  
  push_release:
    name: Push Release
    needs: pack_release
    runs-on: windows-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: artifact
        
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ env.BUILD_VERSION }}
          release_name: Release ${{ env.BUILD_VERSION }}

    - name: Upload binary asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./binary.zip
        asset_name: Toolbox-Inspections-Binary-${{ env.BUILD_VERSION }}.zip
        asset_content_type: application/zip
