name: Toolbox.Inspections

on:
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUILD_VERSION: "0.1.${{ github.run_number }}"

jobs:

  build:
    name: Build
    runs-on: windows-latest  

    steps:
    # - name: List env
    #  run: env
      
    # setup
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Install DocFX
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install docfx

    # - name: Echo Version 
    #  run: echo "Version = ${{ env.BUILD_VERSION }}"
    
    - name: Version Visual Studio SDK projects
      uses: roryprimrose/set-vs-sdk-project-version@v1.0.3
      with:
        version: "${{ env.BUILD_VERSION }}.0"
        assemblyVersion: "${{ env.BUILD_VERSION }}.0"
        fileVersion: "${{ env.BUILD_VERSION }}.0"
        informationalVersion: "${{ env.BUILD_VERSION }}.0"
    
    # Compile the solution
    - name: Compile solution
      run: dotnet build src\Toolbox.Inspections.sln -c Release -o output

    # Test?
    
    # Documentation
    - name: Build Documentation
      working-directory: docfx_project
      run: docfx docfx.json
      continue-on-error: false

    - name: Remove unnecessary files
      run: del output\*.pdb,output\*.dev.json,output\*.deps.json 

    - name: Zip binaries
      uses: TheDoctor0/zip-release@0.6.2
      with:
        filename: 'binary.zip'
        directory: output
        path: Toolbox.Inspections.dll
        type: 'zip'

    # create github release
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      id: create_release
      with:
          tag_name: ${{ env.BUILD_VERSION }}
          release_name: Release ${{ env.BUILD_VERSION }}

    - name: Add zipped binaries
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/binary.zip
        asset_name: Toolbox-Inspections-Binary-${{ env.BUILD_VERSION }}.zip
        asset_content_type: application/zip

    - name: Add nuget package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/Toolbox.Inspections.${{ env.BUILD_VERSION }}.nupkg
        asset_name: Toolbox.Inspections.${{ env.BUILD_VERSION }}.nupkg
        asset_content_type: application/nuget

    - name: Pulish NuGet
    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_TOKEN}}

    # publish documentation
    - name: Publish documentation
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docfx_project/_site
        force_orphan: true
